Repository vegaprotocol/vegacapsule, pull requests merged in 2022-10, with the labels that each got.

#284 fix: swap arg order
  generator/vega/commands.go
Labels: no-changelog, no-issue

#283 feat: test vegacapsule config files + fix install binaries with custom paths
  .github/workflows/start-stop-network-test-configs.yml
  CHANGELOG.md
  installer/installer.go
  jobs/clef.tmpl
Labels: no-issue

#296 fix: fix protocol protocol upgrade proposal command
  .github/workflows/start-stop-network-test-configs.yml
  CHANGELOG.md
  cmd/nodes_protocol_upgrade.go
  generator/visor/generator.go
  installer/installer.go
  net_confs/config_visor_mixed.hcl
  net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl
Labels: no-changelog

#297 feat: update for data node init for pr vega/6500
  CHANGELOG.md
  cmd/network_bootstrap.go
  cmd/template_genesis.go
  generator/datanode/generator.go
  generator/generator.go
  generator/genesis/generator.go
  generator/initiate.go
  go.mod
  importer/genesis.go
Labels: no-issue

#300 feat: use raw template from config
  .github/workflows/start-stop-network-test-configs.yml
  CHANGELOG.md
  config/config.go
  config/parser.go
  net_confs/config.hcl
  net_confs/config_clef.hcl
  net_confs/config_data_node_snapshot.hcl
  net_confs/config_visor_mixed.hcl
  net_confs/genesis.tmpl
  net_confs/node_set_templates/default/data_node_full.tmpl
  net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl
Labels: no-issue

#302 Revert "feat: use raw template from config"
  .github/workflows/start-stop-network-test-configs.yml
  CHANGELOG.md
  config/config.go
  config/parser.go
  net_confs/config.hcl
  net_confs/config_clef.hcl
  net_confs/config_data_node_snap.hcl
  net_confs/config_visor_mixed.hcl
  net_confs/genesis.tmpl
  net_confs/node_set_templates/default/data_node_full.tmpl
  net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl
Labels: no-changelog, no-issue

#303 feat: use raw template from config
  .github/workflows/start-stop-network-test-configs.yml
  CHANGELOG.md
  config/config.go
  config/parser.go
  generator/faucet/generator.go
  net_confs/config.hcl
  net_confs/config_clef.hcl
  net_confs/config_data_node_snapshot.hcl
  net_confs/config_visor_mixed.hcl
  net_confs/genesis.tmpl
  net_confs/node_set_templates/default/data_node_full.tmpl
  net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl
  nomad/job_runner.go
  nomad/job_runner_defaults.go
  types/types.go
Labels: no-issue
