Repository vegaprotocol/vegacapsule, pull requests merged in 2022-09, with the labels that each got.

#249 feat: allow to specify resources for docker tasks
  CHANGELOG.md
  config/config.go
  net_confs/config.hcl
  nomad/job_runner_defaults.go
Labels: no-issue

#250 feat: update clef addresses
  jobs/clef.tmpl
  net_confs/config_clef.hcl
Labels: no-changelog, no-issue

#264 fix: Clef wallet generation panic
  generator/vega/generator.go
Labels: bug, no-changelog, no-issue

#267 fix: update clef
  generator/vega/clef.go
  generator/vega/generator.go
  jobs/clef.tmpl
  net_confs/config_clef.hcl
Labels: no-changelog, no-issue

#271 chore: update Postgres image
  net_confs/config.hcl
  net_confs/config_clef.hcl
  net_confs/config_external_postgres.hcl
  net_confs/config_frontends.hcl
  net_confs/config_sentry_datanode.hcl
  net_confs/config_visor_only.hcl
Labels: no-changelog, no-issue
