Repository vegaprotocol/vegacapsule, pull requests merged in 2022-08, with the labels that each got.

#216 Removed old network param
  CHANGELOG.md
  net_confs/config_checkpoint.hcl
  net_confs/config_example.hcl
  net_confs/config_snapshot.hcl
  net_confs/genesis.tmpl
Labels: enhancement

#218 ci: remove protos branch after merging protos repository into vega core
  Jenkinsfile
Labels: no-changelog, no-issue

#221 feat: downgrade tendermint
  CHANGELOG.md
  generator/tendermint/generator.go
  generator/tendermint/templates.go
  go.mod
  go.sum
  net_confs/config_checkpoint.hcl
  net_confs/config_example.hcl
  net_confs/config_nullchain.hcl
  net_confs/config_snapshot.hcl
  net_confs/node_set_templates/default/tendermint_full.tmpl
  net_confs/node_set_templates/default/tendermint_validators.tmpl
  net_confs/node_set_templates/sentry/tendermint_full.tmpl
  net_confs/node_set_templates/sentry/tendermint_sentry-0.tmpl
  net_confs/node_set_templates/sentry/tendermint_sentry-1.tmpl
  net_confs/node_set_templates/sentry/tendermint_sentry-2.tmpl
  net_confs/node_set_templates/sentry/tendermint_validators.tmpl
  net_confs/stagnet_config.hcl
Labels: no-issue

#224 docs: update binary install docs
  install_vega_bins.md
  readme.md
Labels: no-changelog, no-issue

#211 feat: improve import for tendermint keys
  CHANGELOG.md
  cmd/network_start.go
  cmd/network_stop.go
  importer/tendermint.go
  importer/wallets.go
  nomad/client.go
  nomad/client_allocs.go
  nomad/job_runner.go
Labels: no-issue

#248 feat: remove --no-version-check flag from vega wallet in the importer module
  CHANGELOG.md
  importer/vega.go
Labels: no-issue
