Repository vegaprotocol/vegacapsule, pull requests merged in 2022-11, with the labels that each got.

#308 feat: disable de-history for common network configs
  net_confs/node_set_templates/default/data_node_full.tmpl
  net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl
Labels: no-changelog, no-issue

#312 fix: update project manage action
  .github/workflows/project_managment.yml
Labels: no-changelog, no-issue

#313 fix: out of date project action update query
  .github/workflows/add_issues_to_project.yml
Labels: no-changelog, no-issue

#311 fix: visor templating fixes
  generator/config_overwrite.go
  generator/visor/templates.go
  ports/processes.go
Labels: no-changelog, no-issue

#318 fix: add-issue-to-project errors
  .github/workflows/add_issues_to_project.yml
  .github/workflows/project_managment.yml
Labels: no-changelog, no-issue

#317 Couple of small fixes found
  generator/datanode/templates.go
  generator/faucet/generator.go
  generator/vega/templates.go
  generator/visor/templates.go
  generator/wallet/generator.go
  go.mod
  go.sum
  net_confs/config.hcl
  net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl
  net_confs/node_set_templates/default/visor_config.tmpl
  ports/processes.go
Labels: no-changelog, no-issue

#323 fix: fix protocol upgrade proposal
  CHANGELOG.md
  commands/vega.go
Labels: no-issue

#325 fix: remove unused files - add logger to clef job
  generator/nomad/nomad.go
  generator/pre_generate_jobs.go
  jobs/clef.tmpl
  net_confs/node_set_templates/default/visor_config.tmpl
  nomad/runner/config.go
  test_helpers/protocolupgrade/main.go
Labels: no-changelog, no-issue

#327 chore: add info about destroying the network between config changes
  readme.md
Labels: no-changelog

#335 feat: fix missing port in the data-node de history config
  net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl
  net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl
Labels: no-changelog

#340 fix: brach name on project manage action
  .github/workflows/project_managment.yml
Labels: no-changelog, no-issue

#338 Support more than 9 nodes
  CHANGELOG.md
  net_confs/config.hcl
  net_confs/node_set_templates/default/data_node_full.tmpl
  net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl
  net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl
  net_confs/node_set_templates/default/tendermint_full.tmpl
  net_confs/node_set_templates/default/tendermint_validators.tmpl
  net_confs/node_set_templates/default/vega_full.tmpl
  net_confs/node_set_templates/default/vega_full_visor.tmpl
  net_confs/node_set_templates/default/vega_full_visor_snap.tmpl
  net_confs/node_set_templates/default/vega_validators.tmpl
  net_confs/node_set_templates/default/vega_validators_clef.tmpl
  nomad/job_runner_defaults.go
  nomad/runner/config.go
Labels: enhancement

#341 fix: remove hardcoded bootstrap peers
  .gitignore
  cmd/template_node_sets.go
  generator/datanode/generator.go
  generator/datanode/templates.go
  generator/generator.go
  go.mod
  go.sum
  net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl
  net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl
Labels: no-changelog

#346 fix: Ethereum use ws instead of http
  net_confs/config.hcl
  net_confs/config_checkpoint.hcl
  net_confs/config_clef.hcl
  net_confs/config_data_node_snapshot.hcl
  net_confs/config_example.hcl
  net_confs/config_external_postgres.hcl
  net_confs/config_frontends.hcl
  net_confs/config_nullchain.hcl
  net_confs/config_sentry_datanode.hcl
  net_confs/config_snapshot.hcl
  net_confs/config_visor_mixed.hcl
  net_confs/config_visor_only.hcl
  net_confs/stagnet_config.hcl
Labels: no-changelog

#301 feat: add docs generator
  cmd/docs/hcl_description.md
  cmd/docs/main.go
  cmd/docs/template_ctx_description.md
  config.md
  config/config.go
  config/docker_config.go
  config/ethereum_config.go
  config/faucet_config.go
  config/network_config.go
  config/node_config.go
  config/nomad_config.go
  config/template_node_config.go
  config/wallet_config.go
  docsgenerator/generator.go
  docsgenerator/generator_helpers.go
  docsgenerator/markdown.go
  docsgenerator/types.go
  generator/datanode/generator.go
  generator/datanode/templates.go
  generator/faucet/generator.go
  generator/genesis/template.go
  generator/tendermint/generator.go
  generator/tendermint/templates.go
  generator/vega/generator.go
  generator/vega/templates.go
  generator/visor/generator.go
  generator/wallet/generator.go
  go.mod
  go.sum
  net_confs/config_checkpoint.hcl
  net_confs/config_example.hcl
  net_confs/config_nullchain.hcl
  net_confs/config_snapshot.hcl
  net_confs/node_set_templates/default/tendermint_full.tmpl
  net_confs/node_set_templates/default/tendermint_validators.tmpl
  net_confs/node_set_templates/sentry/tendermint_full.tmpl
  net_confs/node_set_templates/sentry/tendermint_sentry-0.tmpl
  net_confs/node_set_templates/sentry/tendermint_sentry-1.tmpl
  net_confs/node_set_templates/sentry/tendermint_sentry-2.tmpl
  net_confs/node_set_templates/sentry/tendermint_validators.tmpl
  net_confs/stagnet_config.hcl
  readme.md
  templates.md
  types/node_set.go
  types/probes.go
  types/types.go
Labels: documentation, no-changelog

#350 chore: update FE config to run with latest core version
  net_confs/config_frontends.hcl
Labels: vegacapsule, no-changelog, no-issue
